spring:
  application:
    name: tool-insert

  datasource:
    url: jdbc:oracle:thin:@103.21.149.190:1521:orcl
    username: ${DB_USERNAME:TAIXE247_TMP}
    password: ${DB_PASSWORD_DEV:TaiXe247123202511}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: INFO
    com.example.toolinsert: INFO
server:
  port: 8082
app:
  import:
    skip-blank-rows: true
    max-rows: 10000
    batch-size: 200
